spring:
  cloud:
    nacos:
      discovery:
        server-addr: 
  application:
    name: mall-auth
  redis:
    host: 
    port: 6379
    password: 
  session:
    store-type: redis
    timeout: 30m
server:
  port: 20000
logging:
  level:
    com.sunseeker.mall: error
