spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.28.172.116:8848
  application:
    name: mall-auth
  redis:
    host: r-bp1ce2df5bd99b44pd.redis.rds.aliyuncs.com
    port: 6379
    password: Sunseeker123456
  session:
    store-type: redis
    timeout: 30m
server:
  port: 20000
logging:
  level:
    com.sunseeker.mall: error