spring:
  datasource:
    username: 
    password: 
    url: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 
  application:
    name: mall-order
  redis:
    host: r-bp1ce2df5bd99b44pd.redis.rds.aliyuncs.com
    port: 6379
    password: Sunseeker123456
  session:
    store-type: redis
    timeout: 30m
  rabbitmq:
    host: 
    username: 
    password: 
    listener:
      simple:
        acknowledge-mode: manual
    port: 5672
    virtual-host: sunseeker
    publisher-confirms: true
    publisher-returns: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000

mall:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300
