spring:
  datasource:
    username: vivvivvv
    password: Vivivi201206
    url: jdbc:mysql://rm-bp165rp2q1i9a9kyuio.mysql.rds.aliyuncs.com:3306/mall_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 172.28.172.116:8848
  application:
    name: mall-seller


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10001
