spring:
  cloud:
    nacos:
      discovery:
        server-addr: 
  application:
    name: mall-cart
  redis:
    host: 
    port: 6379
    password: 
  session:
    store-type: redis
    timeout: 30m

# 自定义线程池参数
mall:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300

server:
  port: 18001

