spring:
  cloud:
    nacos:
      discovery:
        server-addr: 
    alicloud:
      access-key: 
      secret-key: 
      oss:
        endpoint: 
  application:
    name: mall-third-party
server:
  port: 30000
