spring:
  datasource:
    username: 
    password: 
    url: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 
    alicloud:
      access-key: 
      secret-key: 
      oss:
        endpoint: 
  application:
    name: mall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 
    port: 6379
    password: 
  cache:
    type: redis
    redis:
      time-to-live: 360000000
  thymeleaf:
    cache: false

  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.sunseeker.mall: error
mall:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300
